id: I5F94E07C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:41:02+00:00'
last_modified: '2022-06-07T16:24:07.589537+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ10401
  title: འདུལ་བའི་ཊཱིཀ་ཆེན་ལེགས་བཤད་སྐལ་བཟང་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    443C:
      image_group_id: I1KG11745
      title: ''
      total_pages: 494
      order: 1
      base_file: 443C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
