id: P002946
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:30:09.560603
source_metadata:
  id: bdr:W4CZ10401
  title: འདུལ་བའི་ཊཱིཀ་ཆེན་ལེགས་བཤད་སྐལ་བཟང་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    d651dcc736ff4915b58a1cc6c32b31f1:
      image_group_id: I1KG11745
      title: ''
      volume_number: 1
      total_pages: 494
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
